/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    events: Event;
    'partner-opportunities': PartnerOpportunity;
    posts: Post;
    profiles: Profile;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'partner-opportunities': PartnerOpportunitiesSelect<false> | PartnerOpportunitiesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  strictDraftTypes: true;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Applied technical work — the primary proof that students build real things.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Specific and concrete — name the system or problem, not just the technology. e.g. "Inventory Tracker for Mid-Ohio Food Collective" rather than "Web App Project."
   */
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug?: string | null;
  /**
   * One sentence — what this project is. Shown on project list cards.
   */
  summary: string;
  /**
   * What real problem or need prompted this project? Write it so someone outside the program understands why it mattered — this is what employers read first.
   */
  problem: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Name the actual languages, frameworks, platforms, and tools — not categories. e.g. "PostgreSQL, Next.js, AWS Lambda," not "a database and cloud services."
   */
  technologies: {
    name: string;
    id?: string | null;
  }[];
  /**
   * Every student who worked on this project. Their profile will link back here — make sure they're added before publishing.
   */
  contributors: (number | Profile)[];
  /**
   * What got built or shipped, and what changed as a result. Concrete outcomes, not "gained experience."
   */
  outcomes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Evidence: repo links, writeups, demos, deliverables.
   */
  artifacts?:
    | {
        label: string;
        url?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Which of Build / Engage / Publish does this project represent? Most projects are Build; tag Engage or Publish too if mentorship or a writeup was a core part of the work.
   */
  pillars?: ('build' | 'engage' | 'publish')[] | null;
  coverImage?: (number | null) | Media;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Students, team members, faculty, and alumni featured on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  name: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug?: string | null;
  profileType: 'student' | 'team' | 'faculty' | 'alum';
  /**
   * e.g. "B.S. Computer Science" or "M.S. Data Analytics" — helps employers read the profile in context.
   */
  program?: string | null;
  gradYear?: number | null;
  /**
   * Where this student's work led. Optional — leave the type blank to show no outcome.
   */
  outcome?: {
    /**
     * Shown as a prominent pill on the student card.
     */
    type?:
      | ('internship' | 'co-op' | 'new-position' | 'full-time-offer' | 'promotion' | 'research-role' | 'grad-school')
      | null;
    /**
     * Optional specifics, e.g. "SWE Intern, Nationwide". Factual and concrete — see kk-voice.
     */
    detail?: string | null;
  };
  /**
   * Two or three sentences in your own voice. Specific interests and what you've worked on read better than general career-goal statements.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  avatar?: (number | null) | Media;
  /**
   * GitHub, LinkedIn, portfolio site, deployed projects — anything that lets an employer see more of your work.
   */
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Narrative of involvement not already captured by linked Projects.
   */
  contributions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploaded images and files referenced by other collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility — describe what the image shows.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Workshops, code reviews, employer sessions, and other Engage activities.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug?: string | null;
  /**
   * Workshop, code review, employer session, or other Engage activity — pick the closest match so the Get Involved page can group these sensibly.
   */
  eventType: 'workshop' | 'code-review' | 'employer-session' | 'talk' | 'other';
  /**
   * What happens at this event and who it's for — prospective attendees should know what to expect before signing up.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate: string;
  endDate?: string | null;
  location?: string | null;
  isOnline?: boolean | null;
  facilitators?: (number | Profile)[] | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Partner-submitted project intake — reviewed and scoped by faculty.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-opportunities".
 */
export interface PartnerOpportunity {
  id: number;
  /**
   * Short name for the proposed project.
   */
  title: string;
  organization: string;
  contactName: string;
  contactEmail: string;
  /**
   * Describe the problem or task in plain terms. This is scoped, faculty-overseen student work, not open-ended consulting — describe something bounded enough for a student team to complete in a term.
   */
  problem: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Bounded scope — what's realistically deliverable by students with faculty oversight. Not open-ended consulting. What's explicitly in and out of scope?
   */
  scope: string;
  estimatedEffort: 'small' | 'medium' | 'term-length';
  desiredTechnologies?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Faculty member overseeing this opportunity once it's matched to a student project.
   */
  facultyOverseer?: (number | null) | User;
  /**
   * Tracked by faculty during intake review — not shown publicly.
   */
  status: 'submitted' | 'under-review' | 'accepted' | 'declined' | 'active' | 'complete';
  termAvailability?: string | null;
  /**
   * Internal only — not shown publicly.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Admin/editor accounts for the CMS. Not visible on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins manage users and all content; editors manage content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Writeups, reflections, and case studies — the Publish pillar made visible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug?: string | null;
  /**
   * The student (or faculty moderator) writing this post. Shows on the public post and links to their profile.
   */
  author: number | Profile;
  /**
   * Short summary shown on the blog list and in page metadata.
   */
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'partner-opportunities';
        value: number | PartnerOpportunity;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  problem?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  contributors?: T;
  outcomes?: T;
  artifacts?:
    | T
    | {
        label?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  pillars?: T;
  coverImage?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventType?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  isOnline?: T;
  facilitators?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-opportunities_select".
 */
export interface PartnerOpportunitiesSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  contactName?: T;
  contactEmail?: T;
  problem?: T;
  scope?: T;
  estimatedEffort?: T;
  desiredTechnologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  facultyOverseer?: T;
  status?: T;
  termAvailability?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  profileType?: T;
  program?: T;
  gradYear?: T;
  outcome?:
    | T
    | {
        type?: T;
        detail?: T;
      };
  bio?: T;
  avatar?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  contributions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Content for the public About page — edit without a deploy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  heading: string;
  /**
   * What Kite & Key IT is, its connection to Franklin CSM programs, and the three pillars explained in prose.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short note naming the faculty oversight model — supports the "bounded" partner framing before partners reach the Partner With Us page.
   */
  facultyModeratorNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  facultyModeratorNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}